info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:21:06.358Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:21:09.931Z"}
error: 
    status - 500 
    message - ValidationError: "mailid" is required 
    url - /api/v1/users/newuser 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T13:24:31.100Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:27:49.898Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:27:53.425Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:28:29.127Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:28:39.155Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:28:43.036Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:28:55.766Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:28:59.207Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:31:18.746Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:31:22.161Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:32:04.567Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:32:10.258Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:32:48.788Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:32:52.341Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:39:27.179Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:39:30.661Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:41:28.063Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:41:31.446Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:42:22.335Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:42:26.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:43:56.364Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:44:01.226Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:44:33.667Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:44:36.719Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:48:00.666Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:48:04.175Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T13:48:53.523Z"}
info: Connected to the database. {"timestamp":"2022-06-26T13:48:56.637Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:24:06.345Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:24:09.661Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:30:23.316Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:30:26.547Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:30:37.255Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:30:40.033Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:30:48.684Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:31:05.167Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:31:10.489Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:32:25.964Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:32:29.711Z"}
error: 
    status - 500 
    message - TypeError: _user.default.findone is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-06-26T14:33:13.235Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:33:41.961Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:33:45.175Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.findone is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:25)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-06-26T14:33:51.180Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:36:56.229Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:36:59.308Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'findone')
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:30)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-06-26T14:37:02.557Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:37:59.820Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:38:03.383Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:38:33.544Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:38:36.466Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:41:39.044Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:41:42.589Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:44:23.615Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:44:26.731Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.findone is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:25)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-06-26T14:44:30.376Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:45:06.419Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:45:09.409Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.findone is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:25)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-06-26T14:45:12.222Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:46:18.779Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:46:22.197Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.findone is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - GET 
    IP - ::1
   {"timestamp":"2022-06-26T14:46:27.769Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:58:31.119Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:58:34.503Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.findone is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T14:59:11.517Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T14:59:48.780Z"}
info: Connected to the database. {"timestamp":"2022-06-26T14:59:52.090Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.findone is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:21)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T14:59:54.789Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:00:07.217Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:00:15.184Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.findone is not a function
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:21)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:116:19)
    at Layer.handle [as handle_request] (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T15:00:17.531Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:01:04.597Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:01:07.701Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:04:59.741Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:05:03.217Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:05:12.328Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:05:15.710Z"}
error: 
    status - 500 
    message - ReferenceError: DATABASE is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:22)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T15:06:01.122Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:07:29.642Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:07:33.863Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:12:21.198Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:12:24.444Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:13:16.627Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:13:19.884Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:16:44.098Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:16:47.483Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:16:59.946Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:17:03.093Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:17:38.287Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:17:41.495Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:18:07.100Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:18:10.813Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:18:36.105Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:18:39.244Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:19:33.352Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:19:37.202Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:20:19.264Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:20:22.349Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:21:54.281Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:21:57.683Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:25:14.254Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:25:17.682Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:25:52.492Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:26:01.800Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:26:09.104Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:26:12.097Z"}
error: 
    status - 500 
    message - ReferenceError: DATABASE is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:22)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T15:27:39.097Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:29:02.347Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:29:05.523Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:29:44.525Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:29:47.475Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:30:22.241Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:32:47.880Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:32:51.890Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:33:20.040Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:33:23.712Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:34:59.404Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:35:03.271Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.find is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T15:36:53.269Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:38:25.241Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:38:28.966Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:38:40.415Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:38:43.280Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.FindOne is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T15:38:58.169Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:39:33.449Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:39:36.646Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.findOne is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T15:41:16.334Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:43:00.496Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:43:04.675Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:43:12.427Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:43:15.459Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.findOne is not a function
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:21)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:116:19)
    at Layer.handle [as handle_request] (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\express\lib\router\index.js:284:15 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T15:43:21.562Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:43:45.665Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:43:48.543Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:44:48.478Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:44:51.660Z"}
error: 
    status - 500 
    message - TypeError: _mongodb.Db.findOne is not a function
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:27)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T15:45:08.126Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:48:34.196Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:48:37.604Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'findOne')
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:60:32)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.login (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:58:19)
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\controllers\/user.controller.js:118:36)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T15:48:59.865Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:49:50.575Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:49:55.230Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T15:51:41.141Z"}
info: Connected to the database. {"timestamp":"2022-06-26T15:51:44.468Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:00:16.350Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:00:29.022Z"}
info: Connected to the database. {"timestamp":"2022-06-26T16:00:32.588Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:18:25.291Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:18:30.916Z"}
info: Connected to the database. {"timestamp":"2022-06-26T16:18:34.044Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:22:15.800Z"}
info: Connected to the database. {"timestamp":"2022-06-26T16:22:19.115Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:22:48.179Z"}
info: Connected to the database. {"timestamp":"2022-06-26T16:22:51.154Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:65:20)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T16:23:09.106Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:23:33.290Z"}
info: Connected to the database. {"timestamp":"2022-06-26T16:23:37.570Z"}
error: 
    status - 500 
    message - ReferenceError: req is not defined
    at _callee2$ (C:\Users\ankan\My_Fundo\My_Fundoo_Project\src\services\/user.service.js:65:20)
    at tryCatch (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\ankan\My_Fundo\My_Fundoo_Project\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-06-26T16:24:03.684Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:24:52.688Z"}
info: Connected to the database. {"timestamp":"2022-06-26T16:24:55.868Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:27:36.522Z"}
info: Connected to the database. {"timestamp":"2022-06-26T16:27:39.846Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:29:15.127Z"}
info: Connected to the database. {"timestamp":"2022-06-26T16:29:18.725Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:29:40.234Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:35:30.689Z"}
info: Connected to the database. {"timestamp":"2022-06-26T16:35:33.916Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:37:23.834Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:37:33.386Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T16:37:39.529Z"}
info: Connected to the database. {"timestamp":"2022-06-26T16:37:43.127Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-06-26T17:19:26.433Z"}
info: Connected to the database. {"timestamp":"2022-06-26T17:19:29.634Z"}
